#!/bin/bash
if [ -z "$1" ]; then
    echo "IP not provided as argument"
    exit 1
fi
ssh-keygen -F $1 >/dev/null && ssh-keygen -R $1 
ssh-keyscan -H $1 >> ~/.ssh/known_hosts
sshpass -p "YOUR-PASSWORD" ssh "YOUR-USERNAME"@$1
